name: Daily Weather ETL Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  etl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest test_etl.py -v
        
    - name: Debug Environment
      run: |
        echo "Current working directory: $(pwd)"
        echo "Listing repository contents:"
        ls -la
        echo "Checking for .github directory:"
        ls -la .github/
        echo "Checking for secrets directory:"
        ls -la .github/workflows/
        
    - name: Run ETL pipeline
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY || 'test_key' }}
      run: |
        echo "Checking environment variables..."
        echo "API Key length: ${#OPENWEATHER_API_KEY}"
        if [ "$OPENWEATHER_API_KEY" = "test_key" ]; then
          echo "Warning: Using test API key. This is for testing purposes only."
          echo "For production use, please add your OpenWeather API key as a repository secret."
        fi
        echo "Proceeding with ETL pipeline..."
        python extract.py
        python transform.py
        python load.py
        
    - name: Upload output files
      uses: actions/upload-artifact@v4
      with:
        name: weather-data
        path: output/
        if-no-files-found: error 