name: Daily Weather ETL Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  etl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest test_etl.py -v
        
    - name: Run ETL pipeline
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        echo "Checking environment variables..."
        if [ -z "$OPENWEATHER_API_KEY" ]; then
          echo "Error: OPENWEATHER_API_KEY is not set"
          echo "Please make sure you have added the OPENWEATHER_API_KEY secret in your repository settings"
          echo "Go to: Settings > Secrets and variables > Actions > New repository secret"
          exit 1
        fi
        echo "API key is set, proceeding with ETL pipeline..."
        python extract.py
        python transform.py
        python load.py
        
    - name: Upload output files
      uses: actions/upload-artifact@v4
      with:
        name: weather-data
        path: output/
        if-no-files-found: error 